### ISSUE TITLE
FileNotFoundError when executing skedulord schedule schedule.yml

### ISSUE THREAD

**Issue by rmania** [koaning/skedulord#46]
Want to schedule a py script that is at the exact location as shown in this screenshot and that I specify in a `schedule.yml`
![image](https://user-images.githubusercontent.com/8605612/121544968-651fd200-ca0a-11eb-9fc2-969a1ad416f2.png)

when I execute:
`(venv) (base) C:\Users\XXXX\XXXXX\tv_bi\packages\tvbi>python -m skedulord schedule schedule.yml` 
I receive a rather long `FileNotFoundError` from the crontab.py as shown below. Cannot seem to fix it no matter how I change the paths. 
(the `schedule.yml` is located in the folder from where I run the command above). I run this on a remote windows server.  

`Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\programdata\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Userss\XXXX\XXXXX\tv_bi\packages\tvbi\venv\lib\site-packages\skedulord\__main__.py", line 173, in <module>
    app()
  File "C:\Userss\XXXX\XXXXX\tv_bi\packages\tvbi\venv\lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\Userss\XXXX\XXXXX\tv_bi\packages\tvbi\venv\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\XXXX\XXXXX\\tv_bi\packages\tvbi\venv\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Userss\XXXX\XXXXX\tv_bi\packages\tvbi\venv\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\XXXX\XXXXX\tv_bi\packages\tvbi\venv\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\XXXX\XXXXX\tv_bi\packages\tvbi\venv\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\XXXX\XXXXX\tv_bi\packages\tvbi\venv\lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Users\XXXX\XXXXX\tv_bi\packages\tvbi\venv\lib\site-packages\skedulord\__main__.py", line 57, in schedule
    Cron(config).set_new_cron()
  File "C:\Users\XXXX\XXXXX\tv_bi\packages\tvbi\venv\lib\site-packages\skedulord\cron.py", line 49, in set_new_cron
    cron = CronTab(user=self.settings[0]["user"])
  File "C:\Users\XXXX\XXXXX\tv_bi\packages\tvbi\venv\lib\site-packages\crontab.py", line 228, in __init__
    self.read(tabfile)
  File "C:\Users\XXXX\XXXXX\tv_bi\packages\tvbi\venv\lib\site-packages\crontab.py", line 291, in read
    (out, err) = open_pipe(CRONCMD, l='', **self.user_opt).communicate()
  File "C:\Users\XXXX\XXXXX\tv_bi\packages\tvbi\venv\lib\site-packages\crontab.py", line 190, in open_pipe
    return sp.Popen(args, stdout=sp.PIPE, stderr=sp.PIPE, env=env)
  File "c:\programdata\anaconda3\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\programdata\anaconda3\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Het systeem kan het opgegeven bestand niet vinden
`

**Comment by koaning** [comment]
Ah! You're using skedulord on a Windows machine! That's something that I've never tried before. 

Just to check, are you able to run the command via; 

```
python -m skedulord run jobname1 "python script.py" --retry 3 --wait 60
```

Part of me is wondering if this is a windows system permissions thing. But let's wait and see what happens when you try to run the command directly.

**Comment by koaning** [comment]
Just to check, any feedback?

**Comment by koaning** [comment]
I think Windows doesn't even support cron. I could be wrong though.
